// Angular/Angular2SPA/src/app/components/shared/navbar/navbar.component.ts
import { Component , OnInit} from '@angular/core';
import { Router } from '@angular/router';
//import { Route } from '@angular/router;



@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html'
})
export class NavbarComponent implements OnInit{
  constructor(private router:Router){}
  ngOnInit(){}

  buscarHeroe(termino:string){
    console.log(termino);
    this.router.navigate(['/buscar',termino] );
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
    <a class="navbar-brand" href="#">
        <img src="/assets/img/A-64.png" width="30" height="30" alt="">
      </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <!-- active -->
        <li class="nav-item" routerLinkActive="active">
          <a class="nav-link" [routerLink] ="['home']">Home </a>
        </li>
        <li class="nav-item" routerLinkActive="active">
          <a class="nav-link" [routerLink]="['heroes']">Heroes</a>
        </li>
        <li class="nav-item" routerLinkActive="active">
            <a class="nav-link" [routerLink]="['about']">About</a>
          </li>

      </ul>

      <form class="form-inline my-2 my-lg-0">
        <input 
              class="form-control mr-sm-2" 
              type="search" placeholder="Buscar héroe" aria-label="Search" 
              (keyup.enter) ="buscarHeroe(buscarTexto.value)"
              #buscarTexto>
        <button
              (click)="buscarHeroe(buscarTexto.value)" 
              class="btn btn-outline-primary my-2 my-sm-0" type="button">Buscar
        </button>
      </form>

    </div>
  </nav>

// ReactJS/NavbarRouterProyectReactJS/src/components/NavBar.js
import React, {Component} from 'react';
import { Link } from 'react-router-dom';
import logo from './react-logo.png';
import '../styles/NavBar.css';

class NavBar extends Component{

  render(){
    return(
      <div className="container-fluid">

            <nav className="navbar navbar-expand-lg navbar-light bg-light">
              <a className="navbar-brand " href="#">
                <img className="navbar-logo" src={logo} alt="Logo" />
              </a>
              <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
              </button>

              <div className="collapse navbar-collapse" id="navbarSupportedContent">
                <ul className="navbar-nav mr-auto">
                  <li className="nav-item navbar-listitem active ">
                    <Link className="nav-link" to="/">Home <span className="sr-only">(current)</span></Link>
                  </li>
                  <li className="nav-item navbar-listitem">
                    <Link className="nav-link" to="/bio">Bio</Link>
                  </li>
                  <li className="nav-item navbar-listitem">
                    <Link className="nav-link" to="/description">Description</Link>
                  </li>
                  <li className="nav-item navbar-listitem">
                    <Link className="nav-link disabled" to="/contact-us">Contact us</Link>
                  </li>
                </ul>

              </div>
            </nav>

      </div>
    );
  }

}

export default NavBar;
