// ReactJS/NavbarRouterProyectReactJS/src/components/NavBar.js
import React, {Component} from 'react';
import { Link } from 'react-router-dom';
import logo from './react-logo.png';
import '../styles/NavBar.css';

class NavBar extends Component{

  render(){
    return(
      <div className="container-fluid">

            <nav className="navbar navbar-expand-lg navbar-light bg-light">
              <a className="navbar-brand " href="#">
                <img className="navbar-logo" src={logo} alt="Logo" />
              </a>
              <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
              </button>

              <div className="collapse navbar-collapse" id="navbarSupportedContent">
                <ul className="navbar-nav mr-auto">
                  <li className="nav-item navbar-listitem active ">
                    <Link className="nav-link" to="/">Home <span className="sr-only">(current)</span></Link>
                  </li>
                  <li className="nav-item navbar-listitem">
                    <Link className="nav-link" to="/bio">Bio</Link>
                  </li>
                  <li className="nav-item navbar-listitem">
                    <Link className="nav-link" to="/description">Description</Link>
                  </li>
                  <li className="nav-item navbar-listitem">
                    <Link className="nav-link disabled" to="/contact-us">Contact us</Link>
                  </li>
                </ul>

              </div>
            </nav>

      </div>
    );
  }

}

export default NavBar;

// Angular/Angular6Authapp/src/app/components/navbar/navbar.component.ts
import { Component} from '@angular/core';

import { AuthService } from '../../services/auth.service';


@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styles: []
})
export class NavbarComponent {

  constructor(private auth: AuthService) {
    auth.handleAuthentication();
   }

  login(){
    this.auth.login();
  }

  salir(){
    this.auth.logout();
  }

}

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">AuthApp</a>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item" routerLinkActive="active">
        <a class="nav-link" [routerLink]="['home']">Home</a>
      </li>
      <li class="nav-item" routerLinkActive="active">
        <a class="nav-link" [routerLink]="['precios']">Precios</a>
      </li>

      <li class="nav-item" routerLinkActive="active"
          *ngIf="auth.isAuthenticated()">
        <a class="nav-link" [routerLink]="['protegida']">Protegida</a>
      </li>
    </ul>

    <span class="navbar-text">

      <button (click)="login()"
              *ngIf="!auth.isAuthenticated()"
              type="button"
              class="btn btn-outline-primary btn-sm">Ingresar</button>


      <button (click)="salir()"
              type="button"
              *ngIf="auth.isAuthenticated()"
              class="btn btn-outline-primary btn-sm">Salir</button>

    </span>

  </div>
</nav>
